version : '3'
services:
  mongodb-server: 
    container_name: locker_mongo_db
    image: 'mongo'
    restart: always
    ports: 
      - "27018:27017"
  web:
    container_name: locker_web
    build: . 
    ports: 
      - "3499:80"