name: Run Tests

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile.test --tag tchelidze/locker-test
    - name: Run the Tests
      run: docker run tchelidze/locker-test