name: Docker

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.test --tag tchelidze/locker-test:$(date +%s)
    - name: Run the Tests
      run: docker run tchelidze/locker-test