name: Publish Image To DockerHub

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with: 
        name: tchelidze/locker-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}